### ISSUE TITLE
./doc.pl --no-exe does not produce a valid user guide

### ISSUE THREAD

**Issue by dwsteele** [disco-stu/pkg-pgbackrest#2]
I believe I saw somewhere that you were producing the docs with the --no-exe option.  This option is meant for testing and will not produce a valid user guide.  To produce the user guide correctly Docker must be installed and all containers built with test.pl --vm-build.

If I'm wrong about this then there's no problem but I want to make sure.  The docs have a caching mechanism but it is not ready for prime time.  I may be able to make that work, or we could just ship man with the initial release (with a link on the man page to the website).

**Comment by disco-stu** [comment]
Thant's a problem. You're right, the documentation is build with "--no-exe" (debian/rules). What's the difference between the docs created with and without --no-exe? 

I would really like to skip the docker part. At the moment the package is only build on my local system (inside a chroot), but latest when the package is uploaded it will be build by the buildds (debian)  and on jenkins (apt.postgresql.org). Both inside a chroot. Moreover, debci (debian continuous integration)  will build and test the package inside a lxc container (iirc). I could try to bootstrap the test environment on each run inside the chroot or lxc container. However, I would really like to omit this part.

As far is I can see we have four options:
1. Pass through the hole process. Including docker setup run the tests and the documentation.
2. Add Support for building the documentation without the use of docker.
3. Build release tarballs that includes the documentation.
4. Don't ship the documentation with the debian package at all.

I would prefer either option 2 or 3.

Simply ship a link to the man page isn't enough. The debian policy says each file installed into the PATH need it's own man page.

**Comment by dwsteele** [comment]
Without --no-exe all the examples in the user guide are actually executed and output captured.  The user guide is built in a dynamic way to ensure that all the commands actually _work_.  Also, the user guide can be run on Debian/Ubuntu or RHEL 6 to give different output.  If you look at the guide you generated all the output will be defaulted to "Output suppressed for testing".

There is a caching scheme but it is fairly primitive and won't quite work for this case.  I'm working on something better but don't have too much time today.  It's a holiday weekend here and I'll be gone the next few days.  I may be able to get it done this morning, though.

In general, though, I agree that we should target option 2 or 3.

**Comment by dwsteele** [comment]
OK, there's a new branch that implements an execution cache so the docs can be built even when there is no Docker environment.  Use this branch (https://github.com/pgbackrest/pgbackrest/tree/dev-cache). 

You'll need to use the following command in your rules file:

```
perl $(CURDIR)/doc/doc.pl --out=man --out=html --cache-only --var=project-url-root=index.html
```

Let me know how that goes.

**Comment by disco-stu** [comment]
Looks good. Thanks, that will simplify the build a lot.
Do you know when you release 1.02 (approximately)?

**Comment by dwsteele** [comment]
Well, I was hoping you could test from that branch before I commit to master and do a release.  I'd like to make sure this is going to work.  BTW, you should change the doc command to:

```
perl $(CURDIR)/doc/doc.pl --out=man --out=html --cache-only --var=project-url-root=index.html --exclude=backlog
```

This is so the backlog is not included as part of the package docs.

**Comment by dwsteele** [comment]
Better yet, if you can give me instructions for building the package I'll add it to my integration tests.

**Comment by disco-stu** [comment]
I've tested the command on your dev-cache branch on my machine [1]. The current debian version is 1.01-1 which doesn't contain the latest changes. I can't change the rules file at the moment.

I build the package using gbp buildpackage (git-buildpackage), but the simplest way (IMHO) to build the package is:

> $ git clone https://github.com/disco-stu/pkg-pgbackrest.git
> $ cd pkg-pgbackrest
> $ origtargz        # this will pull in the last version listet in debian/changelog, currently: 1.01
> $ dpkg-buildpackage -us -uc

You will need the following packages:
- build-essential
- devscripts
- txt2man

[1]:

> $ perl doc/doc.pl --out=man --out=html --cache-only --var=project-url-root=index.html --exclude=backlog
> 2016-06-01 10:33:45.742 T00   INFO: render man output
> 2016-06-01 10:33:45.930 T00   INFO: render html output
> 2016-06-01 10:33:45.931 T00   INFO:     render out: command
> 2016-06-01 10:33:46.116 T00   INFO:         process section: introduction
> 2016-06-01 10:33:46.118 T00   INFO:         process section: command-archive-get
> 2016-06-01 10:33:46.169 T00   INFO:         process section: command-archive-push
> 2016-06-01 10:33:46.228 T00   INFO:         process section: command-backup
> 2016-06-01 10:33:46.319 T00   INFO:         process section: command-expire
> 2016-06-01 10:33:46.352 T00   INFO:         process section: command-help
> 2016-06-01 10:33:46.353 T00   INFO:         process section: command-info
> 2016-06-01 10:33:46.400 T00   INFO:         process section: command-restore
> 2016-06-01 10:33:46.488 T00   INFO:         process section: command-start
> 2016-06-01 10:33:46.511 T00   INFO:         process section: command-stop
> 2016-06-01 10:33:46.540 T00   INFO:         process section: command-version
> 2016-06-01 10:33:46.622 T00   INFO:     render out: configuration
> 2016-06-01 10:33:46.752 T00   INFO:         process section: introduction
> 2016-06-01 10:33:46.753 T00   INFO:         process section: section-archive
> 2016-06-01 10:33:46.759 T00   INFO:         process section: section-backup
> 2016-06-01 10:33:46.780 T00   INFO:         process section: section-command
> 2016-06-01 10:33:46.784 T00   INFO:         process section: section-expire
> 2016-06-01 10:33:46.793 T00   INFO:         process section: section-general
> 2016-06-01 10:33:46.825 T00   INFO:         process section: section-log
> 2016-06-01 10:33:46.836 T00   INFO:         process section: section-restore
> 2016-06-01 10:33:46.853 T00   INFO:         process section: section-stanza
> 2016-06-01 10:33:46.890 T00   INFO:     render out: index
> 2016-06-01 10:33:47.009 T00   INFO:         process section: introduction
> 2016-06-01 10:33:47.012 T00   INFO:         process section: features
> 2016-06-01 10:33:47.033 T00   INFO:         process section: getting-started
> 2016-06-01 10:33:47.037 T00   INFO:         process section: contributions
> 2016-06-01 10:33:47.039 T00   INFO:         process section: support
> 2016-06-01 10:33:47.043 T00   INFO:         process section: recognition
> 2016-06-01 10:33:47.053 T00   INFO:     render out: release
> 2016-06-01 10:33:47.248 T00   INFO:         process section: introduction
> 2016-06-01 10:33:47.250 T00   INFO:         process section: development
> 2016-06-01 10:33:47.264 T00   INFO:         process section: current
> 2016-06-01 10:33:47.270 T00   INFO:         process section: supported
> 2016-06-01 10:33:47.283 T00   INFO:         process section: unsupported
> 2016-06-01 10:33:47.465 T00   INFO:     render out: user-guide
> 2016-06-01 10:33:47.609 T00   INFO:         process section: introduction
> 2016-06-01 10:33:47.613 T00   INFO:         process section: concept
> 2016-06-01 10:33:47.621 T00   INFO:         process section: installation
> 2016-06-01 10:33:47.640 T00   INFO:         process section: quickstart
> 2016-06-01 10:33:47.714 T00   INFO:         process section: backup
> 2016-06-01 10:33:47.745 T00   INFO:         process section: retention
> 2016-06-01 10:33:47.773 T00   INFO:         process section: restore
> 2016-06-01 10:33:47.821 T00   INFO:         process section: pitr
> 2016-06-01 10:33:47.885 T00   INFO:         process section: backup-host
> 2016-06-01 10:33:47.919 T00   INFO:         process section: start-stop
> 2016-06-01 10:33:47.939 T00   INFO:         process section: replication
> 
> $ find doc/output 
> doc/output
> doc/output/html
> doc/output/html/default.css
> doc/output/html/release.html
> doc/output/html/user-guide.html
> doc/output/html/command.html
> doc/output/html/logo.png
> doc/output/html/configuration.html
> doc/output/html/index.html
> doc/output/html/favicon.png
> doc/output/man
> doc/output/man/pgbackrest.1.txt
> 
> $ grep -r "suppressed" doc/output | wc -l
> 0

**Comment by disco-stu** [comment]
FWIW: I saw you pushed a 1.02dev tag. I've prepared a branch (1.02dev) based on that tarball.

**Comment by dwsteele** [comment]
I have a branch somewhere with more changes but I can't find it and can't log on to my work computer at the moment.  I tested the packages and I'd like to make a few changes but I'm ready to tag 1.02 in the morning and we can go from there.

**Comment by dwsteele** [comment]
1.02 is now tagged and I submitted PR #3 with a few changes.
